# Gebruik de officiële Nginx image als basisimage
FROM nginx:latest

# Maak buildtime.txt aan met de huidige datum en tijd in UTC
RUN date > /usr/share/nginx/html/buildtime.txt

# Kopieer de inhoud van de html-directory naar de Nginx-server
COPY html /usr/share/nginx/html

# Exposeer poort 80 in de container
EXPOSE 80
